#Sources 
:sources: 
  Habit: 
    :poll_interval: 300
 
:development: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/api/application/
:test: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/api/application/
:production: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/api/application/
