#sdk: "/Users/lefnire/.rvm/gems/ruby-1.9.2-p290/gems/rhodes-3.3.1"
sdkversion: 3.3.0
name: habits-mobile
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: com.rhomobile.habits-mobile
  BundleURLScheme: habits-mobile
wp:
  productid: ac45cdf0-38cc-012f-da6a-58b035f5dd72
symbian:
  uid: 0xee9318f9
android:
  version: 2.1
extensions:
  - json
  - another-extension
